#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm


export PATH="~/bin:$PATH"
export PATH="~/.linuxbrew/bin:$PATH"
export PATH="~/.gem/ruby/1.8/bin:$PATH"
export PATH="$HOME/neovim/bin:$PATH"

source ~/dotfiles/.aliases
source ~/dotfiles/.inputrc
